### PR TITLE
Implement Microsoft Teams exporter

### PR DESCRIPTION
**Pull request by demikl**
New exporter: Microsoft Teams

image

### CODE REVIEW

**Comment by demikl** [comment]
I've not based my work on the `master ` branch, but from the `v0.3.6` tag, because the `master `branch seems to be polluted by `vendors/` file.

**Comment by justinbarrick** [comment]
Thanks for the PR. Please base it on master.

**Comment by demikl** [comment]
> 
> 
> Thanks for the PR. Please base it on master.

Done.

**Comment by tycoles** [comment]
Nice work, @demikl! I'm excited to see this merged 👍

**Pull request merged**
